kind: Service
apiVersion: v1
metadata:
  name: sukus-patient-visit-openapi-ui
spec:
  selector:
    pod: sukus-patient-visit-be-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
